// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import AppCss from "./App.css";

var classes = AppCss;

function App(Props) {
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  return React.createElement("div", {
              className: classes.App
            }, React.createElement("header", undefined, React.createElement("p", undefined, "Hello Vite + Rescript!!!"), React.createElement("p", undefined, React.createElement("button", {
                          onClick: (function (param) {
                              return Curry._1(setCount, (function (count) {
                                            return count + 1 | 0;
                                          }));
                            })
                        }, "count is: " + String(match[0])))));
}

var make = App;

export {
  classes ,
  make ,
  
}
/* classes Not a pure module */
